// Automatically generated by astro-icon
// 05458f9995e61140a72f9ceaa6a467664ea560a0caeeee23524f6e57646ff07e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "android"
		| "astro"
		| "banner"
		| "css"
		| "firebase"
		| "git"
		| "github"
		| "html"
		| "java"
		| "js"
		| "link"
		| "mysql"
		| "node"
		| "php"
		| "react"
		| "react2";
}