// Automatically generated by astro-icon
// 14ce5f1081703f57e602c4ff4bea068c93f70d0822aae320c9704a190fcefbe4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "android"
		| "astro"
		| "banner"
		| "contact"
		| "css"
		| "custom"
		| "email"
		| "firebase"
		| "git"
		| "github"
		| "html"
		| "java"
		| "js"
		| "link"
		| "linkedIn"
		| "mobile"
		| "mysql"
		| "node"
		| "php"
		| "react"
		| "react2"
		| "web";
}