// Automatically generated by astro-icon
// f3e4a024ea52d7b96182c1d284324d1c3b143f6998924c85e35fa8833986ad81

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astro"
		| "banner"
		| "css"
		| "github"
		| "html"
		| "js"
		| "link"
		| "php";
}